"""empty message

Revision ID: 095dc55d8f28
Revises: 96dcd34b2b97
Create Date: 2023-05-02 18:10:40.120656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '095dc55d8f28'
down_revision = '96dcd34b2b97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('postme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extra', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('extra', sa.VARCHAR(), nullable=True),
    sa.Column('address', sa.VARCHAR(), nullable=True),
    sa.Column('telephone', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('postme')
    # ### end Alembic commands ###
