"""empty message

Revision ID: 2e8ca1befb4a
Revises: b6bff13c5f3a
Create Date: 2024-03-25 19:17:56.775254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e8ca1befb4a'
down_revision = 'b6bff13c5f3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fees', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('arrears', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('index', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('index')
        batch_op.drop_column('arrears')
        batch_op.drop_column('fees')

    # ### end Alembic commands ###
