"""empty message

Revision ID: 48aeb6114401
Revises: 5e269aba5285
Create Date: 2024-06-16 19:38:05.047163

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48aeb6114401'
down_revision = '5e269aba5285'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schools', sa.String(), nullable=True),
    sa.Column('year', sa.String(), nullable=True),
    sa.Column('fees', sa.String(), nullable=True),
    sa.Column('arrears', sa.String(), nullable=True),
    sa.Column('index', sa.String(), nullable=True),
    sa.Column('guardian', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student')
    # ### end Alembic commands ###
