"""empty message

Revision ID: 5e269aba5285
Revises: 9eec13d58e48
Create Date: 2024-06-06 21:10:02.072344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e269aba5285'
down_revision = '9eec13d58e48'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('index')
        batch_op.drop_column('schools')
        batch_op.drop_column('year')
        batch_op.drop_column('fees')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fees', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('schools', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('index', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
