"""empty message

Revision ID: 9eec13d58e48
Revises: 2e8ca1befb4a
Create Date: 2024-03-25 20:19:24.977683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eec13d58e48'
down_revision = '2e8ca1befb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schools', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('year', sa.String(), nullable=True))
        batch_op.drop_column('work')
        batch_op.drop_column('fullname')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fullname', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('work', sa.VARCHAR(), nullable=True))
        batch_op.drop_column('year')
        batch_op.drop_column('schools')

    # ### end Alembic commands ###
